dmlm/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using dmlm;
using dmlm.Models;

namespace dmlm.Controllers
{
    [RoutePrefix("Location")]
    public class LocationsController : ApiController
    {
        private Models.LocationModel locationModel = new Models.LocationModel();
        private Models.InventoryLocationsModel InventoryLocationModel = new Models.InventoryLocationsModel();
        private dmlmEntities db = new dmlmEntities();

        // GET: api/Locations
        [ResponseType(typeof(Models.LocationModel.Location))]
        [Route("GetLocations")]
        public IHttpActionResult GetLocations()
        {
            //var serviceProviderID = 0;
            //var userID = 0;
            //int.TryParse(Request.Headers.GetValues("ServiceProviderID").First(), out serviceProviderID);
            //int.TryParse(Request.Headers.GetValues("UserID").First(), out userID);
            return Ok(locationModel.GetLocations(1));
        }

        // GET: api/Locations/5
        [ResponseType(typeof(Models.LocationModel.Location))]
        [Route("GetLocation/{id:int}")]
        public IHttpActionResult GetLocation(int id)

        {
            var serviceProviderID = 0;
            var userID = 0;
            int.TryParse(Request.Headers.GetValues("ServiceProviderID").First(), out serviceProviderID);
            int.TryParse(Request.Headers.GetValues("UserID").First(), out userID);
            var location = locationModel.GetLocation(serviceProviderID, id);
            if (location == null)
            {
                return NotFound();
            }

            return Ok(location);
        }

        // GET: api/Locations/5
        [ResponseType(typeof(Models.LocationModel.Location))]
        [Route("GetLocation/{id:int}/{regionid:int}")]
        public IHttpActionResult GetLocationByRegion(int id, int regionid)
        {
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return NotFound();
            }

            return Ok(location);
        }

        // GET: /Location/GetInventoryCount
        [ResponseType(typeof(LocationProductCounts))]
        [Route("GetInventoryCount/{id:int}/{locationid:int}")]
        public IHttpActionResult GetInventoryCount(int id, int locationid)
        {
            var locationCounts = 
                InventoryLocationModel.GetInventoryCountsByLocation(locationid);
            if (locationCounts == null)
            {
                return NotFound();
            }

            return Ok(locationCounts);
        }

        // PUT: api/Locations/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutLocation(int id, Location location)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != location.Id)
            {
                return BadRequest();
            }

            db.Entry(location).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LocationExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Locations
        [ResponseType(typeof(Location))]
        public IHttpActionResult PostLocation(Location location)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Locations.Add(location);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (LocationExists(location.Id))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = location.Id }, location);
        }

        // DELETE: api/Locations/5
        [ResponseType(typeof(Location))]
        public IHttpActionResult DeleteLocation(int id)
        {
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return NotFound();
            }

            db.Locations.Remove(location);
            db.SaveChanges();

            return Ok(location);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool LocationExists(int id)
        {
            return db.Locations.Count(e => e.Id == id) > 0;
        }
    }
}

dmlm/Controllers/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dmlm;
using Microsoft.AspNet.Identity;
using System.Web.Caching;

namespace dmlm.Controllers
{
    public class UsersAdminController : Controller
    {
        private dmlmEntities db = new dmlmEntities();
        private Models.PageModel.Page UserPage = new Models.PageModel.Page();
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            var pageModel = HttpContext.Cache.Get("pageModel");
            if (pageModel != null)
                UserPage = (Models.PageModel.Page)pageModel;
            ViewBag.Layout = UserPage.Layout;
        }
        // GET: UsersAdmin
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: UsersAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: UsersAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,firstName,lastName,title,employeeNumber,emailAddress,phoneNumber,cellPhoneNumber,isActive,createDate,serviceProviderId,password,role")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: UsersAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,firstName,lastName,title,employeeNumber,emailAddress,phoneNumber,cellPhoneNumber,isActive,createDate,serviceProviderId,password,role")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: UsersAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dmlm/Views/Widgets/_Agents.cshtml
@model dmlm.Models.PageModel.Page
    @{ 
        var agentModel = new dmlm.Models.AgentModel().GetAgent(Model);
    }
<script src="~/Scripts/popup.js"></script>
@Styles.Render("~/Content/Site.css")
<div style="background-color:lightgray;">
    <div class="col-lg-8" style="margin-top:20px; border: 2px solid black; padding:10px;">
        @{
            <h2>@Model.Widgets.Where(w => w.WidgetType.Id == 1).FirstOrDefault().Name <a id="region" style="float: right">North West Region</a></h2>

            foreach (var agent in agentModel.Take(10))
            {
                <div class="col-lg-6">
                    <text style="color:crimson;">@agent.Fullname</text>
                    @Html.ActionLink("Edit", "Edit", "UsersAdmin", new { id = agent.Id }, new { @class = "regionEdit" })
                </div>
                if (agentModel.Count() > 10)
                {
                    <div style="float:right;"><a href="">...</a></div>
                }
            }
        }
    </div>
    <div class="col-sm-3 col-md-3 pull-right" style="padding-top:10px;">
        <form role="search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    var myPopup = new smq.Popup({
        title: 'Popup.js Example',
        innerHtml: '<div><a id="region" style="float: right">South West Region</a><br/><a id="regionClose" style="float: right">South West Region</a><br/></div>'
    });
    $(document).ready(function () {
        $("#region").click(function () {
            myPopup.show();
        });
    });
</script>

dmlm/Views/Widgets/_Locations.cshtml
@model dmlm.Models.PageModel.Page
@{
    var agentModel = new dmlm.Models.AgentModel().GetAgent(Model);
    var agents = agentModel.ToArray();
    
    //System.Web.UI.ScriptManager.RegisterStartupScript(this, this.GetType(), "CallMyFunction", "DrawChart()", true);
}
<script src="~/Scripts/Chart.min.js"></script>
<div class="col-lg-6" style="width: 100%">
    <div>
        <canvas id="myChart" height="400" width="400"></canvas>
    </div>
</div>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            //labels: ["Mark Kidwell", "Ben Mcadoo", "Kimate Richards", "Green", "Purple", "Orange"],
            labels: ["Mark Kidwell", "Ben Mcadoo", "Kimate Richards", "Michael Jackson", "Rogers Nelson", "Leia Organa"],
            datasets: [{
                label: '# of Site Visits',
                data: [12, 15, 3, 5, 19, 3]
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>

dmlm/Views/Widgets/_Map_Pin.cshtml
@model dmlm.Models.PageModel.Page

<div class="col-lg-6">
    <div style="font-size:28px; font-weight:bold">@Model.Widgets.Where(w => w.WidgetType.Id == (int)dmlm.Models.PageModel.Widgets.MapPins).FirstOrDefault().Name</div>
    <style>
        .mapPin {
            height: 500px;
            width: 500px;
        }
    </style>
    <div id="mapPin" class="mapPin"></div>
    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('mapPin'), {
                zoom: 12,
                center: { lat: 37.775, lng: -122.4194200 }
            });
            setMarkers(map);
        }
            var agents = [
              ['Mark Kidwell', 37.772, -122.410, 4],
              ['Kimate Richards', 37.7751, -122.4094014, 5],
              ['Ben Macadoo', 37.77546, -122.4194207, 3],
              ['Michael Jackson', 37.7751447, -122.419443545, 6],
              ['Rogers Nelson', 37.7844447, -122.4084014, 2],
              ['Leia Organa', 37.76514562, -122.41558447, 1]
            ];
            function setMarkers(map) {
                var image = {
                    url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
                    // This marker is 20 pixels wide by 32 pixels high.
                    size: new google.maps.Size(20, 32),
                    // The origin for this image is (0, 0).
                    origin: new google.maps.Point(0, 0),
                    // The anchor for this image is the base of the flagpole at (0, 32).
                    anchor: new google.maps.Point(0, 32)
                };
                // Shapes define the clickable region of the icon. The type defines an HTML
                // <area> element 'poly' which traces out a polygon as a series of X,Y points.
                // The final coordinate closes the poly by connecting to the first coordinate.
                var shape = {
                    coords: [1, 1, 1, 20, 18, 20, 18, 1],
                    type: 'poly'
                };
                for (var i = 0; i < agents.length; i++) {
                    var agent = agents[i];
                    var marker = new google.maps.Marker({
                        position: { lat: agent[1], lng: agent[2] },
                        map: map,
                        icon: image,
                        shape: shape,
                        title: agent[0],
                        zIndex: agent[3]
                    });
                }
            }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLVr49f8utsLypg6SRNfGriBswv2yY78I&callback=initMap">
    </script>
</div>

dmlm/Views/Widgets/_Maps.cshtml
@model dmlm.Models.PageModel.Page

<div class="col-lg-6">
    <div style="font-size:28px; font-weight:bold">@Model.Widgets.Where(w => w.WidgetType.Id == (int)dmlm.Models.PageModel.Widgets.Maps).FirstOrDefault().Name</div>
@*<style>
    #map {
        height: 500px;
        width: 500px;
    }
</style>

<div id="map"></div>
<script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 10
        });
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLVr49f8utsLypg6SRNfGriBswv2yY78I&callback=initMap"
        async defer></script>
</div>*@
    <style>
    .mapRoute {
        height: 500px;
        width: 500px;
    }

    #panel {
    position: absolute;
    top: 5px;
    left: 50%;
    margin-left: -180px;
    z-index: 5;
    background-color: #fff;
    padding: 5px;
    border: 1px solid #999;
    }

    #bar {
    width: 240px;
    background-color: rgba(255, 255, 255, 0.75);
    margin: 8px;
    padding: 4px;
    border-radius: 4px;
    }

    #autoc {
    width: 100%;
    box-sizing: border-box;
    }
    </style>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=drawing,places"></script>
    <script>
        var apiKey = 'AIzaSyBLVr49f8utsLypg6SRNfGriBswv2yY78I';

var map;
var drawingManager;
var placeIdArray = [];
var polylines = [];
var snappedCoordinates = [];

function initialize() {
  var mapOptions = {
    zoom: 17,
    center: { lat: 37.775, lng: -122.4194200 }
  };
  map = new google.maps.Map(document.getElementById('map'), mapOptions);

  // Adds a Places search box. Searching for a place will center the map on that
  // location.
  map.controls[google.maps.ControlPosition.RIGHT_TOP].push(
      document.getElementById('bar'));
  var autocomplete = new google.maps.places.Autocomplete(
      document.getElementById('autoc'));
  autocomplete.bindTo('bounds', map);
  autocomplete.addListener('place_changed', function() {
    var place = autocomplete.getPlace();
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);
    }
  });

  // Enables the polyline drawing control. Click on the map to start drawing a
  // polyline. Each click will add a new vertice. Double-click to stop drawing.
  drawingManager = new google.maps.drawing.DrawingManager({
    drawingMode: google.maps.drawing.OverlayType.POLYLINE,
    drawingControl: true,
    drawingControlOptions: {
      position: google.maps.ControlPosition.TOP_CENTER,
      drawingModes: [
        google.maps.drawing.OverlayType.POLYLINE
      ]
    },
    polylineOptions: {
      strokeColor: '#696969',
      strokeWeight: 2
    }
  });
  drawingManager.setMap(map);

  // Snap-to-road when the polyline is completed.
  drawingManager.addListener('polylinecomplete', function(poly) {
    var path = poly.getPath();
    polylines.push(poly);
    placeIdArray = [];
    runSnapToRoad(path);
  });

  // Clear button. Click to remove all polylines.
  $('#clear').click(function(ev) {
    for (var i = 0; i < polylines.length; ++i) {
      polylines[i].setMap(null);
    }
    polylines = [];
    ev.preventDefault();
    return false;
  });
}

// Snap a user-created polyline to roads and draw the snapped path
function runSnapToRoad(path) {
  var pathValues = [];
  for (var i = 0; i < path.getLength(); i++) {
    pathValues.push(path.getAt(i).toUrlValue());
  }

  $.get('https://roads.googleapis.com/v1/snapToRoads', {
    interpolate: true,
    key: apiKey,
    path: pathValues.join('|')
  }, function(data) {
    processSnapToRoadResponse(data);
    drawSnappedPolyline();
    getAndDrawSpeedLimits();
  });
}

// Store snapped polyline returned by the snap-to-road method.
function processSnapToRoadResponse(data) {
  snappedCoordinates = [];
  placeIdArray = [];
  for (var i = 0; i < data.snappedPoints.length; i++) {
    var latlng = new google.maps.LatLng(
        data.snappedPoints[i].location.latitude,
        data.snappedPoints[i].location.longitude);
    snappedCoordinates.push(latlng);
    placeIdArray.push(data.snappedPoints[i].placeId);
  }
}

// Draws the snapped polyline (after processing snap-to-road response).
function drawSnappedPolyline() {
  var snappedPolyline = new google.maps.Polyline({
    path: snappedCoordinates,
    strokeColor: 'black',
    strokeWeight: 3
  });

  snappedPolyline.setMap(map);
  polylines.push(snappedPolyline);
}

// Gets speed limits (for 100 segments at a time) and draws a polyline
// color-coded by speed limit. Must be called after processing snap-to-road
// response.
function getAndDrawSpeedLimits() {
  for (var i = 0; i <= placeIdArray.length / 100; i++) {
    // Ensure that no query exceeds the max 100 placeID limit.
    var start = i * 100;
    var end = Math.min((i + 1) * 100 - 1, placeIdArray.length);

    drawSpeedLimits(start, end);
  }
}

// Gets speed limits for a 100-segment path and draws a polyline color-coded by
// speed limit. Must be called after processing snap-to-road response.
function drawSpeedLimits(start, end) {
    var placeIdQuery = '';
    for (var i = start; i < end; i++) {
      placeIdQuery += '&placeId=' + placeIdArray[i];
    }

    $.get('https://roads.googleapis.com/v1/speedLimits',
        'key=' + apiKey + placeIdQuery,
        function(speedData) {
          processSpeedLimitResponse(speedData, start);
        }
    );
}

// Draw a polyline segment (up to 100 road segments) color-coded by speed limit.
function processSpeedLimitResponse(speedData, start) {
  var end = start + speedData.speedLimits.length;
  for (var i = 0; i < speedData.speedLimits.length - 1; i++) {
    var speedLimit = speedData.speedLimits[i].speedLimit;
    var color = getColorForSpeed(speedLimit);

    // Take two points for a single-segment polyline.
    var coords = snappedCoordinates.slice(start + i, start + i + 2);

    var snappedPolyline = new google.maps.Polyline({
      path: coords,
      strokeColor: color,
      strokeWeight: 6
    });
    snappedPolyline.setMap(map);
    polylines.push(snappedPolyline);
  }
}

function getColorForSpeed(speed_kph) {
  if (speed_kph <= 40) {
    return 'purple';
  }
  if (speed_kph <= 50) {
    return 'blue';
  }
  if (speed_kph <= 60) {
    return 'green';
  }
  if (speed_kph <= 80) {
    return 'yellow';
  }
  if (speed_kph <= 100) {
    return 'orange';
  }
  return 'red';
}

$(window).load(initialize);

    </script>

    <div id="map" class="mapRoute"></div>
    <div id="bar">
        <p class="auto"><input type="text" id="autoc" /></p>
        <p><a id="clear" href="#">Click here</a> to clear map.</p>
    </div>
</div>